spring:
  application:
    name: Festival

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: JWT비밀키

api:
  public-data:
    key: 발급받은 API키